# action.yml
name: "Self-Hosted Runner Job Cleaner"
description: "Cleanup the environment at the end of the job"
branding:
  icon: "trash-2"
  color: "black"
inputs:
  service_ids:
    required: false
    default: ${{ toJSON(job.services.*.id) }}
runs:
  using: "docker"
  image: "Dockerfile"
  post-entrypoint: "/cleanup.sh"
